# -*- coding: utf-8 -*-
"""MLU_logisticCredit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108bmg6H736KMKEGgydnUJlsc_4giKD6c
"""

from sklearn.linear_model import LogisticRegression
import pickle
with open('credit.pkl', 'rb') as f:
  X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)

#dataset já normalizado
X_credit_treinamento

X_credit_treinamento.shape

X_credit_teste.shape

logistic_credit = LogisticRegression(random_state = 1)

logistic_credit.fit(X_credit_treinamento, y_credit_treinamento)

logistic_credit.coef_

previsoes = logistic_credit.predict(X_credit_teste)
previsoes

from sklearn.metrics import accuracy_score, classification_report

accuracy_score(y_credit_teste, previsoes)

from yellowbrick.classifier import ConfusionMatrix
cm = ConfusionMatrix(logistic_credit)
cm.fit(X_credit_treinamento, y_credit_treinamento)
cm.score(X_credit_teste, y_credit_teste)

print(classification_report(y_credit_teste, previsoes))